included:
  - Sources
excluded:
  - Assets
  - Fixtures
  - Tests
  - .build
  - Sources/xcodeproj/String+md5.swift
disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - nesting
  - cyclomatic_complexity
  - file_length
  - todo
line_length:
  warning: 150
  error: 170
