os:
- osx
language: generic
osx_image: xcode9.2
install:
- bundle install
before_script:
- bundle exec danger
- carthage update --platform iOS,macOS
script:
- bundle exec rake ci
after_success:
- bundle exec rake deploy_to_integration
