name: Package

on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: swift build -c release

  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate project
        run: swift package generate-xcodeproj
      - name: Run tests
        run: xcodebuild test -project XcodeProj.xcodeproj -scheme XcodeProj-Package -enableCodeCoverage YES
      - name: Send test coverage report
        run: bash <(curl -s https://codecov.io/bash)

  danger:
    name: Danger
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate project
        run: swift package generate-xcodeproj
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Bundler 2.0.2
        run: gem install bundler --version 2.0.2
      - name: Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
